sonar.projectKey=jenkins-auto-test
sonar.projectName=jenkins-auto-test
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
