print("Hello, world!")  
print("This is a test file named test0123.py")
print("It contains simple print statements.")
print("End of the test file.")              
print("Goodbye, world!")
print("This file is used for testing purposes.")
print("Testing complete.")
print("Final line of the test file.")
print("All tests passed successfully.")
print("Exiting the test file now.")
